#!/bin/sh
set -e

### BEGIN INIT INFO
# Provides:		openerp-server
# Required-Start:	$local_fs $remote_fs $network $time $postgresql
# Required-Stop:	$local_fs $remote_fs $network $time $postgresql
# Should-Start:		$syslog
# Should-Stop:		$syslog
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	OpenERP server
### END INIT INFO

PIDFILE=/var/run/openerp-server.pid
USER=openerp
DAEMON=/opt/code/openerp/openobject-server/openerp-server
CONFIGFILE=/etc/openerp-server.cfg
DAEMON_OPTS="-c ${CONFIGFILE}"


do_start() {
    start-stop-daemon --start --quiet --pidfile ${PIDFILE} --chuid ${USER} --background --make-pidfile --exec ${DAEMON} -- ${DAEMON_OPTS}
}

do_stop() {
    start-stop-daemon --stop --pidfile ${PIDFILE}
}

case "$1" in
    start)
        do_start
        set +e
        ;;
    stop)
        do_stop
        set +e
        ;;
    restart)
        do_stop
        do_start
        set +e
        ;;
    reload)
        echo "Reload not supported - restarting"
        do_stop
        do_start
        set +e
        ;;
    status)
        set +e
        if [ ! -e ${PIDFILE} ]
        then
            echo "PID file doesn't exist"
            exit 1
        fi

        PID_IN_FILE=`cat ${PIDFILE}`
        ps -ef |grep openerp |grep -v grep |grep ${PID_IN_FILE} > /dev/null
        EXIT=$?
        if [ ${EXIT} -ne 0 ]
        then
            echo "Not running"
            exit 1
        else
            echo "Running"
        fi

        ;;
    *)
        echo "Usage: $0 {start|stop|restart|reload|status}"
        set +e
        exit 1
        ;;
esac

exit 0

