---
name: Test Run on PR merge
on:
  pull_request:
    types: [closed]
    branches: [staging]
jobs:
  quick-test:
    if: github.envent.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Do something
    steps:
      - name: Show some output
        run: |-
          echo "Running the workflow!"
          echo "Staging branch exists now"
          echo "Ooh, a dev branch"
          echo "Are we going to see it this time?"
  always-run:
    runs-on: ubuntu-latest
    name: Do something else
    steps:
      - name: Just a little output then
        run: |-
          echo "Should always run on closed PR"
